#!/bin/bash

# SET TOGGLE FILE
TOGGLE="/tmp/nl"

# BUTTONS
case "$BLOCK_BUTTON" in
    3) if [ ! -e "$TOGGLE" ]; then
             touch "$TOGGLE"
         else
             rm "$TOGGLE"
         fi ;;
    4) xbacklight -inc 5 ;;
    5) xbacklight -dec 5 ;;
esac

# TURN ON OR OFF NIGHTLIGHT
if [ ! -e "$TOGGLE" ]; then
    sct
else
    sct 4000
fi

# PRINT OUT
BRIGHTNESS=$(xbacklight | awk '{ printf "%d%%\n", int($1+0.5) }')
echo "$BRIGHTNESS"
echo "$BRIGHTNESS"
if [ -e "$TOGGLE" ]; then
    echo "#FFFF00"
fi
