#!/bin/sh

# SET TOGGLE FILE
TOGGLE=/tmp/time

if [ "$BLOCK_BUTTON" -eq 3 ]; then
  if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
  else
    rm $TOGGLE
  fi
fi

# PRINT OUT
if [ ! -e $TOGGLE ]; then
  date "+%Y-%m-%d %H:%M:%S %:z"
else
  echo "$(date "+%Y-%m-%d") $(chronos)"
fi
