#!/bin/sh

# SET TOGGLE FILE
TOGGLE="/tmp/time"

# BUTTON
if [ "$BLOCK_BUTTON" = "3" ]; then
  if [ ! -e "$TOGGLE" ]; then
    touch "$TOGGLE"
  else
    rm "$TOGGLE"
  fi
fi

# PRINT OUT
if [ ! -e "$TOGGLE" ]; then
  date --iso-8601=seconds
else
  echo "$(date "+%Y-%m-%d")" "$(chronos)"
fi
